spring.application.name=AIQueryApi

server.port=${PORT:8080}

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.max-tokens=1000
spring.ai.google.genai.chat.options.temperature=0.2