spring.application.name=AIQueryApi

server.port=${PORT:8080}
# spring.ai.openai.api-key=${OPENAI_API_KEY}
# spring.ai.openai.base-url=https://api.groq.com/openai
# spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
# spring.ai.openai.chat.options.temperature=0.4
# spring.ai.openai.chat.options.max-tokens=2500

# 1. Tu API KEY de Google (consíguela en https://aistudio.google.com/app/apikey)
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# 2. El modelo que queremos usar
# spring.ai.google.genai.chat.options.model=models/gemini-pro

# 3. Temperatura (0.4 está bien para equilibrio entre creatividad y precisión)
spring.ai.google.genai.chat.options.temperature=0.4

# 4. Para ponerle un termino a las contestaciones, por si entrase en bucle
spring.ai.google.genai.chat.options.max-tokens=2048