spring.application.name=AIQueryApi

server.port=${PORT:8080}

# Tu API KEY de Google
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# Si quieres limitar los tokens de salida de forma global
spring.ai.google.genai.chat.options.max-tokens=1200


